=pod

=head1 NAME

coprt - run oprt command in container

=head1 SYNOPSIS

coprt tool ...

=head1 DESCRIPTION

B<coprt> runs any C<oprt> command in a container based on the F</> using func(1).

For example, the command C<coprt depinst port> will execute C<oprt-depinst port> in a temporary container, based on the real F</>, and the only changes done to the real F</> will be to source, package, build and .cache/oprt directories.

It is a simple way to build ports without installing them and ask for the root password.

It is somehow similar to sysupc(1) from func package.

=cut
