#!/bin/bash

libdir=${BASH_SOURCE%/*}
. $libdir/oprt_lib

declare -A _FOUND

main() {
	(( $# == 1 )) || lib_fatal_errorf '%s' "one argument is required"

	find_ports "$1"

	(( ${#_FOUND[@]} > 0 )) \
		&& show_search_results "$1"
}

find_ports() {
	local _EXPR="[^\\s]*\\s*[^\\s]*.*$1"

	local _FOOTPRINT _DIR _COL _PORT

	while read -r _FOOTPRINT; do
		_DIR=${_FOOTPRINT%/*}
		_PORT=${_DIR##*/}

		_FOUND["$_PORT"]=1
	done < <(
		grep    --regexp="$_EXPR"            \
			--ignore-case                \
			--files-with-matches         \
			-- $PP_PORTS/*/.footprint    \
			   $PORTS_DIR/*/*/.footprint \
		)
}

show_search_results() {
	local _EXPR=$1

	local _PORT _VERSION _C _COL

	for _PORT in "${!_FOUND[@]}"; do
		_COL=( $($libdir/oprt-collections "$_PORT") )

		lib_return_installed_version "$_PORT"
		_VERSION=$return

		lib_show_info 'Name'      "$_PORT"
		lib_show_info 'Installed' "${_VERSION:-no}"

		for _C in "${_COL[@]}"; do
			OPRT_SEARCHING=1 $libdir/oprt-info "$_C/$_PORT"

			awk '{print "/"$3}' < "$_C/$_PORT/.footprint"  \
				| grep --regexp="$_EXPR" --ignore-case \
				| sed 's/^/Match:        /'
		done

		echo ""
	done
}

main "$@"

