#!/bin/bash

. ${BASH_SOURCE%/*}/oprt_lib

main() {
	local _N=${OPRT_WATCH_PROCESSES//[^0-9]/}
	_N=${_N:-5}
	
	local _WATCH
	while read -r _WATCH; do
		check "$(readlink -f "$_WATCH")" &

		local _JOBS=( $(jobs -p) )
		(( ${#_JOBS[@]} < $_N )) \
			|| wait -n
	done < <(
		find -L "${@:-$PWD}" -type f -name .watch
	)

	wait_background_jobs
}

check() {
	local    _WATCH=$1
	local _PORT_DIR=${_WATCH%/*}

	[[ -e "$_PORT_DIR/Pkgfile" ]] \
		|| return

	(cd "$_PORT_DIR" && pkgmk -cs >/dev/null) \
		|| return

	. "$_PORT_DIR/Pkgfile"

	local _UPVER _NAME
	while read -r _UPVER _NAME; do
		[[ $_UPVER != "" ]] || {
			lib_warningf 'URL match failed: %s\n' "$_PORT_DIR"
			continue
		}
		_NAME=${_NAME:-version}
		_NAME=${_NAME//[^a-z_]/}
		local _PORT_VERSION=${!_NAME}
		[[ $_PORT_VERSION == $_UPVER ]] \
			|| lib_warningf '%s: %s -> %s' "$_PORT_DIR" "$_PORT_VERSION" "$_UPVER"
	done < <(sh "$_WATCH")

	return 0
}

wait_background_jobs() {
	local _J

	for _J in $(jobs -p); do
		wait $_J
	done
}

main "$@"
exit 0
